# generated by datamodel-codegen:
#   filename:  list_of_accounts.json
#   timestamp: 2023-08-25T12:26:07+00:00

from pydantic import BaseModel, Field


class Parent(BaseModel):
    mmc: list[str]
    account_id: str = Field(..., alias="accountId")
    is_m_parent: bool = Field(..., alias="isMParent")
    is_m_child: bool = Field(..., alias="isMChild")
    is_multiplex: bool = Field(..., alias="isMultiplex")


class Account(BaseModel):
    id: str
    account_id: str = Field(..., alias="accountId")
    account_van: str = Field(..., alias="accountVan")
    account_title: str = Field(..., alias="accountTitle")
    display_name: str = Field(..., alias="displayName")
    account_alias: str | None = Field(..., alias="accountAlias")
    account_status: int = Field(..., alias="accountStatus")
    currency: str
    type: str
    faclient: bool
    clearing_status: str = Field(..., alias="clearingStatus")
    covestor: bool
    parent: Parent
    desc: str
