# generated by datamodel-codegen:
#   filename:  conids.json
#   timestamp: 2023-08-26T17:48:55+00:00

from pydantic import BaseModel, Field, RootModel


class Contract(BaseModel):
    conid: int
    exchange: str
    is_us: bool = Field(..., alias="isUS")


class Stock(BaseModel):
    name: str
    chinese_name: str | None = Field(..., alias="chineseName")
    asset_class: str = Field(..., alias="assetClass")
    contracts: list[Contract]


class Conids(RootModel[dict[str, list[Stock]]]):
    root: dict[str, list[Stock]]
